
services:
    
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\RequestListener:
        arguments:
              $defaultPerPage: '%default_pagination_per_page%'
        tags:
            - { name: kernel.event_listener, event: kernel.request }


